require "stringio"
require "optparse"
require "json"
require "open-uri"

require "colorize"
require "parslet"
require "csscss/parslet_optimizations"

require "csscss/version"
require "csscss/cli"
require "csscss/types"
require "csscss/redundancy_analyzer"
require "csscss/reporter"
require "csscss/json_reporter"

require "csscss/parser/common"
require "csscss/parser/color"
require "csscss/parser/base"
require "csscss/parser/multi_side_transformer"

require "csscss/parser/css"
require "csscss/parser/background"
require "csscss/parser/list_style"
require "csscss/parser/margin"
require "csscss/parser/padding"
require "csscss/parser/border_width"
require "csscss/parser/border_color"
require "csscss/parser/border_style"
require "csscss/parser/border_side"
require "csscss/parser/border"
require "csscss/parser/outline"
require "csscss/parser/font"

